### ISSUE TITLE
Could not locate the GPIB library

### ISSUE THREAD

**Issue by HaydenS3** [tivek/gpib_ctypes#9]
#### The Error
I'm trying to communicate with an SR770 over GPIB using PyVISA-py. I've successfully communicated with the device on a Windows 10 pc, but attempting to do so on a Windows 11 pc results in the error below. To my knowledge, the only effective difference between the systems is the Windows version.
```
ValueError: gpib_ctypes is installed but could not locate the gpib library.
Please manually load it using:
  gpib_ctypes.gpib.gpib._load_lib(filename)
```
#### Debugging
1. Tried manually loading the library using `gpib._load_lib('C:\\Windows\\SysWOW64\\gpib-32.dll')`
2. Confirmed that NI 488.2 2024 Q3 is installed correctly as I'm able to communicate with the instrument through NI Max.
3. Copied `gpib-32.dll` into System32.
4. Tried using [Object-Oriented API](https://gpib-ctypes.readthedocs.io/en/latest/usage.html#object-oriented-gpib-api) as mentioned in issue #2 .
5. Tried modifying the gpib_ctypes library as mentioned in issue #7.

Any advice or guidance would be greatly appreciated!

**Comment by wcook1957** [comment]
having same problem, 64bit Windows 11 trying to use python package Keithley2600 class

**Comment by HaydenS3** [comment]
Check out [this issue](https://github.com/pyvisa/pyvisa-py/issues/461) I opened on the pyvisa-py repo. It might be helpful for you
